version: "3.9"

Access-Control-Allow-Origin: *

services:
    deno-express-api:
        container_name: deno-express-api
        image: deno
        restart: always
        build:
            context: .
            dockerfile: Dockerfile
            target: base
        ports:
            - "${PORT}:${PORT}"